## estimate_ambient.R
## Two ways to estimate the ambient ("soup") expression profile from data.
##
## (1) ambient_global()     -- the assumption shared by SoupX and DecontX:
##     one global soup profile = the normalised aggregate of background counts.
##
## (2) ambient_structured() -- the bet of this package: the soup is generated by
##     whichever cells LYSED, which is a biased subsample of the tissue. So model
##     the soup as a non-negative mixture of real cell-state programs and recover
##     the per-program "lysis weights" from the empty-droplet pool. As a
##     CORRECTOR this was falsified (see README); it survives as a diagnostic.

#' Global soup profile: normalised aggregate of the empty-droplet pool.
#' @param empty genes x droplets matrix of background counts (dense or sparse).
#' @return length-G probability vector.
#' @export
ambient_global <- function(empty) {
  p <- .row_sums(.as_counts(empty, "empty"))
  if (sum(p) == 0) stop("empty droplets contain no counts", call. = FALSE)
  p / sum(p)
}

## Non-negative least squares via multiplicative updates.
## Solves  min_w ||A w - b||^2  s.t. w >= 0, for non-negative A, b.
## Chosen over Lawson-Hanson to keep the package dependency-free.
.nnls_mu <- function(A, b, iter = 500, eps = 1e-12) {
  w <- rep(1, ncol(A))
  AtA <- crossprod(A)            # K x K
  Atb <- as.numeric(crossprod(A, b))
  for (i in seq_len(iter)) {
    w <- w * (Atb / (as.numeric(AtA %*% w) + eps))
  }
  w[w < 0] <- 0
  w
}

#' Structured soup profile (lysis diagnostic).
#'
#' @param empty genes x droplets background matrix.
#' @param basis genes x K matrix of cell-state program profiles (columns need
#'   not be normalised; they are normalised internally). Supply cluster means
#'   from your filtered cells -- see [cluster_basis()].
#' @return list with $soup (length-G probability vector) and $lysis (length-K
#'   non-negative weights summing to 1; the interpretable output telling you
#'   which populations are contaminating the rest).
#' @export
ambient_structured <- function(empty, basis) {
  basis <- sweep(basis, 2, colSums(basis), "/")     # column-normalise programs
  b <- ambient_global(empty)                        # observed soup profile
  w <- .nnls_mu(basis, b)
  if (sum(w) == 0) w <- rep(1 / length(w), length(w))
  lysis <- w / sum(w)
  names(lysis) <- colnames(basis)
  soup <- as.numeric(basis %*% lysis)
  soup <- soup / sum(soup)
  list(soup = soup, lysis = lysis)
}

#' Derive a program basis (cluster mean profiles) from the observed cells.
#'
#' @param observed genes x cells counts.
#' @param k number of k-means clusters (ignored if `clusters` is given).
#' @param n_hvg top-variance genes used for clustering.
#' @param seed RNG seed.
#' @param clusters optional cluster labels (e.g. from Seurat / SCE); when given,
#'   no clustering is run.
#' @return genes x K matrix, columns are probability vectors.
#' @export
cluster_basis <- function(observed, k = 6, n_hvg = 200, seed = 1, clusters = NULL) {
  observed <- .as_counts(observed, "observed")
  if (is.null(clusters)) clusters <- quick_labels(observed, k = k, n_hvg = n_hvg, seed = seed)
  ks <- sort(unique(clusters))
  basis <- .cluster_sums(observed, clusters, ks)
  ## mean RAW profile per cluster, normalised to a probability vector
  basis <- sweep(basis, 2, pmax(colSums(basis), 1e-300), "/")
  colnames(basis) <- paste0("prog", ks)
  basis
}
