## estimate_ambient.R
## Two ways to estimate the ambient ("soup") expression profile from data.
##
## (1) ambient_global()     -- the assumption shared by SoupX and DecontX:
##     one global soup profile = the normalised aggregate of background counts.
##
## (2) ambient_structured() -- the bet of this package: the soup is generated by
##     whichever cells LYSED, which is a biased subsample of the tissue. So model
##     the soup as a non-negative mixture of real cell-state programs and recover
##     the per-program "lysis weights" from the empty-droplet pool. When lysis is
##     actually uniform this collapses back to the global estimate (good: it means
##     the structured model adds nothing harmful in the regime where the simple
##     assumption is true). When lysis is biased it should be strictly better.

#' Global soup profile: normalised aggregate of the empty-droplet pool.
#' @param empty genes x droplets matrix of background counts.
#' @return length-G probability vector.
ambient_global <- function(empty) {
  p <- rowSums(empty)
  p / sum(p)
}

## Non-negative least squares via multiplicative updates.
## Solves  min_w ||A w - b||^2  s.t. w >= 0, for non-negative A, b.
## Chosen over Lawson-Hanson to keep the package dependency-free.
.nnls_mu <- function(A, b, iter = 500, eps = 1e-12) {
  w <- rep(1, ncol(A))
  AtA <- crossprod(A)            # K x K
  Atb <- as.numeric(crossprod(A, b))
  for (i in seq_len(iter)) {
    w <- w * (Atb / (as.numeric(AtA %*% w) + eps))
  }
  w[w < 0] <- 0
  w
}

#' Structured soup profile.
#'
#' @param empty genes x droplets background matrix.
#' @param basis genes x K matrix of cell-state program profiles (columns need
#'   not be normalised; they are normalised internally). Supply cluster means
#'   from your filtered cells -- see cluster_basis().
#' @return list with $soup (length-G probability vector) and $lysis (length-K
#'   non-negative weights summing to 1; the interpretable output telling you
#'   which populations are contaminating the rest).
ambient_structured <- function(empty, basis) {
  basis <- sweep(basis, 2, colSums(basis), "/")     # column-normalise programs
  b <- rowSums(empty); b <- b / sum(b)              # observed soup profile
  w <- .nnls_mu(basis, b)
  if (sum(w) == 0) w <- rep(1 / length(w), length(w))
  lysis <- w / sum(w)
  soup <- as.numeric(basis %*% lysis)
  soup <- soup / sum(soup)
  list(soup = soup, lysis = lysis)
}

#' Derive a program basis (cluster mean profiles) from the observed cells.
#' Deliberately simple (k-means on log-normalised top-variance genes) so the
#' benchmark does not depend on a particular clustering toolchain. In a real
#' package this would accept Seurat/SCE cluster labels directly.
cluster_basis <- function(observed, k = 6, n_hvg = 200, seed = 1) {
  set.seed(seed)
  cs <- colSums(observed); cs[cs == 0] <- 1
  logn <- log1p(sweep(observed, 2, cs, "/") * 1e4)
  v <- apply(logn, 1, var)
  hvg <- order(v, decreasing = TRUE)[seq_len(min(n_hvg, nrow(logn)))]
  km <- kmeans(t(logn[hvg, ]), centers = k, nstart = 5, iter.max = 50)
  ## mean RAW profile per cluster, normalised to a probability vector
  basis <- vapply(seq_len(k), function(j) {
    m <- rowSums(observed[, km$cluster == j, drop = FALSE])
    m / sum(m)
  }, numeric(nrow(observed)))
  colnames(basis) <- paste0("prog", seq_len(k))
  basis
}
